export const appActions = {
  FETCHING_EVENTS_START: 'FETCHING_EVENTS_START',
  FETCHING_EVENTS_SUCCESS: 'FETCHING_EVENTS_SUCCESS',
  FETCHING_EVENTS_ERROR: 'FETCHING_EVENTS_ERROR',

  FETCHING_EVENT_START: 'FETCHING_EVENT_START',
  FETCHING_EVENT_SUCCESS: 'FETCHING_EVENT_SUCCESS',
  FETCHING_EVENT_ERROR: 'FETCHING_EVENT_ERROR',
};
